### ISSUE TITLE
Cart 도메인 수정

### ISSUE THREAD

**Issue by CocoIsCat** [CocoIsCat/Mini-Project-BE-Refactor#1]
## Description(설명)
- Cart 도메인과 관련된 부분을 수정한다.
## Tasks(New feature)
- [ ] MapStruct로 DTO와 Entity 변환하기
- [x] 적절한 예외 처리 적용하기
- [x] ResponseEntity 활용해서 반환하기
- [x] 기타 이상한 코드 수정하기
